# -*- coding: utf-8 -*-
"""exploratoryassignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jEe_6RE6xa-Ga6S0DSryUbfNTyt2Vi5
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("train.csv")
df.head()

df['datetime'] = pd.to_datetime(df['datetime'])

df.info()

df.isnull().sum()

df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['dayofweek'] = df['datetime'].dt.dayofweek
df['hour'] = df['datetime'].dt.hour

df[["datetime", "year", "month", "dayofweek", "hour"]].head()

season_map = {
    1: 'spring',
    2: 'summer',
    3: 'fall',
    4: 'winter'
}

df['season'] = df['season'].map(season_map)

total_by_year = df.groupby('year')[['casual', 'registered']].sum()
total_by_year

df.groupby('season')['count'].mean()

df.groupby('workingday')['registered'].mean()

df.groupby('workingday')['casual'].mean()

df.groupby(['year','workingday'])[['casual','registered']].mean()

df.groupby(['year','month'])['count'].sum()

df[df['year']==2011].groupby('month')['count'].sum().sort_values()
df[df['year']==2012].groupby('month')['count'].sum().sort_values()

df.groupby('weather')['count'].mean()

df.corr(numeric_only=True)['count'].sort_values(ascending=False)

def period(h):
    if 0 <= h < 6:
        return 'night'
    elif 6 <= h < 12:
        return 'morning'
    elif 12 <= h < 18:
        return 'afternoon'
    else:
        return 'evening'

df['day_period'] = df['hour'].apply(period)

pivot = df.pivot_table(values='count', index='day_period',
                       columns='workingday', aggfunc='mean')
pivot

#Assignment 2

#Step 1
import matplotlib.pyplot as plt
numerical_cols = df.select_dtypes(include="number").columns

df[numerical_cols].hist(figsize=(15,10))
plt.show()

#Step 2
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(15,6))
sns.boxplot(data=df[numerical_cols])
plt.xticks(rotation=45)
plt.show()

#Step 3
mean_working = df.groupby("workingday")["count"].mean()

mean_working.plot(kind="bar")
plt.xlabel("Working Day (0 = No, 1 = Yes)")
plt.ylabel("Mean Rentals")
plt.title("Mean Bike Rentals: Working vs Non-working Days")
plt.show()

#Step 4
import pandas as pd

df = pd.read_csv("train.csv")
df["datetime"] = pd.to_datetime(df["datetime"])
import matplotlib.pyplot as plt

# create month column
df["month"] = df["datetime"].dt.month

# calculate mean rentals per month (both years)
monthly_mean = df.groupby("month")["count"].mean()

# plot
monthly_mean.plot(marker="o")
plt.xlabel("Month")
plt.ylabel("Mean Hourly Rentals")
plt.title("Mean Hourly Bike Rentals by Month (Both Years Combined)")
plt.xticks(range(1, 13))
plt.show()

#Step 5
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("train.csv")
df["datetime"] = pd.to_datetime(df["datetime"])

df["year"] = df["datetime"].dt.year
df["month"] = df["datetime"].dt.month
# mean rentals for each month in each year
monthly_year_mean = df.groupby(["year", "month"])["count"].mean().reset_index()

# create 2 panels (1 row, 2 columns)
fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

# plot for each year separately
for i, year in enumerate(sorted(monthly_year_mean["year"].unique())):
    temp = monthly_year_mean[monthly_year_mean["year"] == year]
    axes[i].plot(temp["month"], temp["count"], marker="o")
    axes[i].set_title(f"Mean Rentals by Month - {year}")
    axes[i].set_xlabel("Month")
    axes[i].set_xticks(range(1, 13))

axes[0].set_ylabel("Mean Hourly Rentals (count)")
plt.tight_layout()
plt.show()

#Step 6
weather= df.groupby("weather")["count"].agg(
    mean="mean",
    std="std",
    n="count"
)

weather["ci"] = 1.96 * weather["std"] / np.sqrt(weather["n"])

plt.errorbar(
    weather.index,
    weather["mean"],
    yerr=weather["ci"],
    fmt="o"
)

plt.xlabel("Weather Category")
plt.ylabel("Mean Rentals")
plt.title("Mean Rentals with 95% CI by Weather")
plt.show()

df['weekday']= df['datetime'].dt.dayofweek

#Step 7
hourly = df.groupby("hour")["count"].mean()

hourly.plot()
plt.xlabel("Hour")
plt.ylabel("Mean Rentals")
plt.title("Mean Hourly Rentals vs Hour of Day")
plt.show()

#step 8
plt.figure(figsize=(10,6))

for day in sorted(df["weekday"].unique()):
    df[df["weekday"] == day].groupby("hour")["count"].mean().plot(label=f"Day {day}")

plt.legend(title="Weekday")
plt.xlabel("Hour")
plt.ylabel("Mean Rentals")
plt.title("Hourly Rentals by Day of Week")
plt.show()

#Step 9
fig, axes = plt.subplots(2, 2, figsize=(14,10), sharex=True, sharey=True)

for ax, season in zip(axes.flatten(), sorted(df["season"].unique())):
    df[df["season"] == season].groupby("hour")["count"].mean().plot(ax=ax)
    ax.set_title(f"Season {season}")
    ax.set_xlabel("Hour")
    ax.set_ylabel("Mean Rentals")

plt.suptitle("Hourly Rentals by Season")
plt.show()

def period(hour):
    if hour < 6:
        return "Night"
    elif hour < 12:
        return "Morning"
    elif hour < 18:
        return "Afternoon"
    else:
        return "Evening"

df["period"] = df["hour"].apply(period)

period_stats = df.groupby(["period", "workingday"])["count"].agg(
    mean="mean",
    std="std",
    n="count"
)

period_stats["ci"] = 1.96 * period_stats["std"] / np.sqrt(period_stats["n"])
period_stats.reset_index(inplace=True)

#Step 10
sns.barplot(
    data=period_stats,
    x="period",
    y="mean",
    hue="workingday",
    capsize=0.2
)

plt.ylabel("Mean Rentals")
plt.title("Mean Rentals by Period of Day (Working vs Non-working)")
plt.show()

num_cols = df.select_dtypes(include=np.number).columns
num_cols

#Step 11
plt.figure(figsize=(12,8))
corr = df[num_cols].corr()

sns.heatmap(corr, cmap="coolwarm", center=0)
plt.title("Correlation Matrix of Numerical Variables")
plt.show()